language: go

services:
- redis-server

go:
  - 1.1
  - 1.2
  - tip

install:
  - go get gopkg.in/bufio.v1
  - go get github.com/golang/glog
  - go get launchpad.net/gocheck
  - go get gopkg.in/redis.v1
